### ISSUE TITLE
Inconsistent POST Endpoint in Documentation: '/events' Mentioned in README, but '/event' Implemented in Code

### ISSUE THREAD

**Issue by dipakja** [agitrubard/java-spring-best-practices#2]
In the README, the POST endpoint for creating an event is documented as /events. However, in the actual code (EventController), the POST mapping is implemented as /event. 

This inconsistency can lead to confusion for users trying to follow the documentation. I recommend updating either the README or the code to ensure the endpoints are consistent.

**Comment by agitrubard** [comment]
@dipakja Thank you so much for bringing this to my attention! 🙌🏼

I completely understand the inconsistency and you’re absolutely right. It seems I missed that detail, and I appreciate you taking the time to point it out.

I will correct this as soon as possible to ensure the endpoint and documentation are aligned. Thanks again for your valuable feedback!
